server:
  port: 8080

spring:
  data:
    mongodb:
      database: demo
      port: 27017
      host: localhost

vehicle:
  attributes:
    basicInformation:
      - brand
      - model
    performance:
      - topSpeed
      - tripMeter
